version: '3.8'
services:
  fastapi:
    image: your_fastapi_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SOME_ENV_VARIABLE=value
